### ISSUE TITLE
CLI struct.error

### ISSUE THREAD

**Issue by Wikilicious** [Wikilicious/pygmc#123]
The device was OFF.
The empty line after `PyGMC - Live GMC Heartbeat` should've had the Geiger Counter model-version.
I was expecting some connection error or something that indicates the device is not ON.
I thought get version worked even when device is off. Is this just a GMC-800 thing?

```
pygmc -p /dev/ttyUSB1 live -t 5
PyGMC - Live GMC Heartbeat

Start=2024-07-18 17:09:11 counts=5
Traceback (most recent call last):
  File "/home/thomaz/tmp/testcli/.venv/bin/pygmc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/thomaz/tmp/testcli/.venv/lib/python3.12/site-packages/pygmc/cli.py", line 159, in main
    _live_flow(args)
  File "/home/thomaz/tmp/testcli/.venv/lib/python3.12/site-packages/pygmc/cli.py", line 119, in _live_flow
    gc.heartbeat_live_print(count=args.time)
  File "/home/thomaz/tmp/testcli/.venv/lib/python3.12/site-packages/pygmc/devices/device_spec404.py", line 359, in heartbeat_live_print
    for i, cps in enumerate(self.heartbeat_live(count=count)):
  File "/home/thomaz/tmp/testcli/.venv/lib/python3.12/site-packages/pygmc/devices/device_spec404.py", line 341, in heartbeat_live
    cps = struct.unpack(">I", raw)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
```

Device was `GMC-800Re1.08`

**Comment by Wikilicious** [comment]
I'm inclined to suspect some VMware/Ubuntu/USB-Cable weirdness. 
It didn't print out version... but it was able to successfully get the version to identify the correct device seen in traceback above.
Additionally, `get_version()` has a len requirement else it raises a timeout error which is not what the traceback shows.

Today installed pygmc==0.14.0, with a GMC-600+ (and device powered on) I get...
```
pygmc live -t 3
PyGMC - Live GMC Heartbeat

Start=2024-08-02 17:41:36 counts=3
 cps=1       | max=1       | total=2           | loop=2         
Finish=2024-08-02 17:41:39
```

Then **remove and reconnect the USB cable** and... now the version is printed.
```
pygmc live -t 3
PyGMC - Live GMC Heartbeat
GMC-600+Re 2.52
Start=2024-08-02 17:47:51 counts=3
 cps=0       | max=1       | total=1           | loop=2         
Finish=2024-08-02 17:47:54
```
